services:
  db:
    image: mysql:8.0
    container_name: devops-product-mysql
    ports:
      - "3307:3306"
    environment:
      # L'erreur venait de l'absence de cette ligne :
      - MYSQL_ROOT_PASSWORD=1122

      # On crée aussi la base et l'utilisateur pour l'appli directement ici
      - MYSQL_DATABASE=product_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1122
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
