spring:
  application:
    name: product-service
  profiles:
    active: dev
#    active: @spring.profiles.active@

server:
  port: 9095
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
