spring:
  application:
    name: product-service
  profiles:
    active: @spring.profiles.active@ # Injecté par Maven lors du build

server:
  port: 9095
  shutdown: graceful # Arrêt propre pour le CI/CD

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus # Pour le monitoring ELK/Grafana

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method # Trie les méthodes par GET, POST, etc.
  api-docs:
    path: /v3/api-docs
