name: Publish to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # ÉTAPE CLÉ : On nettoie TOUT (Username et Version) pour Docker
      - name: Prepare Metadata
        id: meta
        run: |
          # 1. Version du pom.xml
          RAW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          # 2. Nettoyage : Passage en minuscules (Docker n'accepte pas les majuscules dans le repo)
          CLEAN_USER=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          
          echo "owner=${CLEAN_USER}" >> $GITHUB_OUTPUT
          echo "version=${RAW_VERSION}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Package
        run: mvn clean package -Pprod -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # On utilise les variables nettoyées (outputs de l'étape 'meta')
          tags: |
            ${{ steps.meta.outputs.owner }}/product-service:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.owner }}/product-service:${{ steps.meta.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max